name: food_ordering_app
description: A mobile app for managing food orders with a database.

# The version of the application.
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.3
  path: ^1.8.3
  intl: ^0.20.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

# Assets (if you plan to add any images or other files later)
# assets:
#   - assets/images/

